name: CI Practice

on:
  push:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: s1
        run: echo "Starting CI"
      - name: s2
        run: echo "${{ github.ref }}"
      - name: s3
        run: echo "${{ github.actor }}"
      - name: s4
        run: echo "CI finished successfully"




