name: Example
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: List files (before chechout)
        run: ls -la
      - name: Checkout Code 
        uses: actions/checkout@v4
      - name: List Files (after Checkout )
        run: ls -la
    
